type: app
description: Stackfile de exemplo para teste
template: ottoni-stack-test/template-1
inputs:
  project_version: "0.0.1"
  project_description: "Um projeto criado a partir da stack de teste"
  author_name: "John Doe"
  author_email: "johndoe@mail.com"
# list of plugins to be applied after project creation
plugins:
  - plugin: ottoni-stack-test/plugin-1
  - plugin: ottoni-stack-test/plugin-2
